[package]
name = "vida"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["default", "derive", "unicode"] }
rand = { version = "0.8", features = ["default", "small_rng"] }
rayon = "1.7"
piston_window = "0.128"

[profile.release]
codegen-units = 1
lto = true
